import { DEFAULT_HOTKEY_SET } from "@/lib/parsingHotkeyCsv";
import { HotkeyLabel, HotkeySet } from "@/types/hotkey";

export const SET_WORD = "Word";
export const SET_POWERPOINT = "PowerPoint";
export const SET_EXCEL = "Excel";
export const SET_OUTLOOK = "Outlook";
export const SET_ONENOTE = "OneNote";
export const SET_CURSOR = "Cursor";
export const SET_CHROME = "Chrome";
export const SET_IE = "Internet Explorer";
export const SET_EXPLORER = "File Explorer";
export const SET_KEYVIZ = "Keyviz";

const GROUP_CLIPBOARD = "Clipboard";
const GROUP_FILE = "File";
const GROUP_EDITING = "Editing";
const GROUP_WINDOW = "Window";
const GROUP_NAVIGATION = "Navigation";
const GROUP_TYPING = "Typing";
const GROUP_FORMATTING = "Formatting";
const GROUP_PROOFING = "Proofing";
const GROUP_SLIDESHOW = "Slideshow";
const GROUP_ARRANGE = "Arrange";
const GROUP_DATA = "Data";
const GROUP_MAIL = "Mail";
const GROUP_CALENDAR = "Calendar";
const GROUP_NOTES = "Notes";
const GROUP_AI = "AI";
const GROUP_VIEW = "View";
const GROUP_GENERAL = "General";
const GROUP_TABS = "Tabs";
const GROUP_PAGE = "Page";
const GROUP_LIBRARY = "Library";
const GROUP_FILES = "Files";
const GROUP_KEYVIZ = "Keyviz";

/**
 * Builds one starter label with a stable id.
 */
const buildingDefaultLabel = (
  set: string,
  name: string,
  combo: string,
  description: string,
  group = "",
): HotkeyLabel => ({
  id: `default-${set}-${combo}`,
  set,
  name,
  combo,
  description,
  group,
});

/**
 * Starter sets bound to common Windows process names.
 */
export const DEFAULT_HOTKEY_SETS: HotkeySet[] = [
  { name: SET_WORD, enabled: true, programs: ["WINWORD.EXE"] },
  { name: SET_POWERPOINT, enabled: true, programs: ["POWERPNT.EXE"] },
  { name: SET_EXCEL, enabled: true, programs: ["EXCEL.EXE"] },
  { name: SET_OUTLOOK, enabled: true, programs: ["OUTLOOK.EXE"] },
  { name: SET_ONENOTE, enabled: true, programs: ["ONENOTE.EXE"] },
  { name: SET_CURSOR, enabled: true, programs: ["Cursor.exe"] },
  { name: SET_CHROME, enabled: true, programs: ["chrome.exe"] },
  { name: SET_IE, enabled: true, programs: ["iexplore.exe"] },
  { name: SET_EXPLORER, enabled: true, programs: ["explorer.exe"] },
  { name: SET_KEYVIZ, enabled: true, programs: [] },
];

/**
 * Starter shortcuts for each default set.
 */
const RAW_DEFAULT_HOTKEY_LABELS: HotkeyLabel[] = [
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Copy",
    "Ctrl+C",
    "Copy the selection",
    GROUP_CLIPBOARD,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Paste",
    "Ctrl+V",
    "Paste from the clipboard",
    GROUP_CLIPBOARD,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Cut",
    "Ctrl+X",
    "Cut the selection",
    GROUP_CLIPBOARD,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Undo",
    "Ctrl+Z",
    "Undo the last action",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Redo",
    "Ctrl+Y",
    "Redo the last action",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Select all",
    "Ctrl+A",
    "Select everything",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Save",
    "Ctrl+S",
    "Save the file",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Open",
    "Ctrl+O",
    "Open a file",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "New",
    "Ctrl+N",
    "Create a new item",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Print",
    "Ctrl+P",
    "Print",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Find",
    "Ctrl+F",
    "Find on the page",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Close",
    "Ctrl+W",
    "Close the window or tab",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Close window",
    "Alt+F4",
    "Close the window",
    GROUP_WINDOW,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Refresh",
    "F5",
    "Reload",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Select address",
    "Ctrl+L",
    "Focus the address bar",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Switch window",
    "Alt+Tab",
    "Switch apps",
    GROUP_WINDOW,
  ),
  buildingDefaultLabel(
    DEFAULT_HOTKEY_SET,
    "Capitalize",
    "Shift+(char)",
    "{char} will be capitalized",
    GROUP_TYPING,
  ),

  buildingDefaultLabel(
    SET_WORD,
    "Bold",
    "Ctrl+B",
    "Bold the selection",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Italic",
    "Ctrl+I",
    "Italicize the selection",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Underline",
    "Ctrl+U",
    "Underline the selection",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Center",
    "Ctrl+E",
    "Center the paragraph",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Left align",
    "Ctrl+L",
    "Align the paragraph left",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Right align",
    "Ctrl+R",
    "Align the paragraph right",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Copy format",
    "Ctrl+Shift+C",
    "Copy the formatting",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Paste format",
    "Ctrl+Shift+V",
    "Paste the formatting",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Save",
    "Ctrl+S",
    "Save the document",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Open",
    "Ctrl+O",
    "Open a document",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Print",
    "Ctrl+P",
    "Print the document",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "New document",
    "Ctrl+N",
    "Create a document",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Close",
    "Ctrl+W",
    "Close the document",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Find",
    "Ctrl+F",
    "Find in the document",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Replace",
    "Ctrl+H",
    "Find and replace",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Hyperlink",
    "Ctrl+K",
    "Insert a hyperlink",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Go to",
    "Ctrl+G",
    "Jump to a page or line",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Spelling",
    "F7",
    "Check spelling",
    GROUP_PROOFING,
  ),
  buildingDefaultLabel(
    SET_WORD,
    "Thesaurus",
    "Shift+F7",
    "Look up a synonym",
    GROUP_PROOFING,
  ),

  buildingDefaultLabel(
    SET_POWERPOINT,
    "Start slideshow",
    "F5",
    "Play from the first slide",
    GROUP_SLIDESHOW,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "Start from current",
    "Shift+F5",
    "Play from this slide",
    GROUP_SLIDESHOW,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "End slideshow",
    "Escape",
    "Leave the show",
    GROUP_SLIDESHOW,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "Black screen",
    "B",
    "Black out during a show",
    GROUP_SLIDESHOW,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "White screen",
    "W",
    "White out during a show",
    GROUP_SLIDESHOW,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "Next slide",
    "PageDown",
    "Go to the next slide",
    GROUP_SLIDESHOW,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "Previous slide",
    "PageUp",
    "Go to the previous slide",
    GROUP_SLIDESHOW,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "New slide",
    "Ctrl+M",
    "Insert a slide",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "Duplicate slide",
    "Ctrl+D",
    "Duplicate the selection",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "Bold",
    "Ctrl+B",
    "Bold the selection",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "Italic",
    "Ctrl+I",
    "Italicize the selection",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "Save",
    "Ctrl+S",
    "Save the deck",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "Open",
    "Ctrl+O",
    "Open a presentation",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "Print",
    "Ctrl+P",
    "Print the deck",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "New presentation",
    "Ctrl+N",
    "Create a presentation",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "Group",
    "Ctrl+G",
    "Group objects",
    GROUP_ARRANGE,
  ),
  buildingDefaultLabel(
    SET_POWERPOINT,
    "Ungroup",
    "Ctrl+Shift+G",
    "Ungroup objects",
    GROUP_ARRANGE,
  ),

  buildingDefaultLabel(
    SET_EXCEL,
    "Edit cell",
    "F2",
    "Edit the active cell",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Format cells",
    "Ctrl+1",
    "Open Format Cells",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Find",
    "Ctrl+F",
    "Find in the sheet",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Replace",
    "Ctrl+H",
    "Find and replace",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Fill down",
    "Ctrl+D",
    "Fill the cells below",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Fill right",
    "Ctrl+R",
    "Fill the cells to the right",
    GROUP_EDITING,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Bold",
    "Ctrl+B",
    "Bold the selection",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "AutoSum",
    "Alt+=",
    "Insert a sum",
    GROUP_DATA,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Create table",
    "Ctrl+T",
    "Make a table",
    GROUP_DATA,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Toggle filter",
    "Ctrl+Shift+L",
    "Turn filters on or off",
    GROUP_DATA,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Select column",
    "Ctrl+Space",
    "Select the column",
    GROUP_DATA,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Select row",
    "Shift+Space",
    "Select the row",
    GROUP_DATA,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Show formulas",
    "Ctrl+`",
    "Show or hide formulas",
    GROUP_DATA,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Insert function",
    "Shift+F3",
    "Insert a function",
    GROUP_DATA,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Go to",
    "F5",
    "Jump to a cell",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Next sheet",
    "Ctrl+PageDown",
    "Go to the next sheet",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Previous sheet",
    "Ctrl+PageUp",
    "Go to the previous sheet",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Save",
    "Ctrl+S",
    "Save the workbook",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Open",
    "Ctrl+O",
    "Open a workbook",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "New workbook",
    "Ctrl+N",
    "Create a workbook",
    GROUP_FILE,
  ),
  buildingDefaultLabel(
    SET_EXCEL,
    "Print",
    "Ctrl+P",
    "Print the sheet",
    GROUP_FILE,
  ),

  buildingDefaultLabel(
    SET_OUTLOOK,
    "New message",
    "Ctrl+N",
    "Start an email",
    GROUP_MAIL,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Reply",
    "Ctrl+R",
    "Reply to the sender",
    GROUP_MAIL,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Reply all",
    "Ctrl+Shift+R",
    "Reply to everyone",
    GROUP_MAIL,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Forward",
    "Ctrl+F",
    "Forward the message",
    GROUP_MAIL,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Send",
    "Ctrl+Enter",
    "Send the message",
    GROUP_MAIL,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Delete",
    "Delete",
    "Delete the item",
    GROUP_MAIL,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Search",
    "Ctrl+E",
    "Search mail",
    GROUP_MAIL,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Mark unread",
    "Ctrl+U",
    "Mark the message unread",
    GROUP_MAIL,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Flag",
    "Ctrl+Shift+G",
    "Flag the message",
    GROUP_MAIL,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Address book",
    "Ctrl+Shift+B",
    "Open the address book",
    GROUP_MAIL,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Send and receive",
    "F9",
    "Check for new mail",
    GROUP_MAIL,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "New appointment",
    "Ctrl+Shift+A",
    "Create a calendar event",
    GROUP_CALENDAR,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Inbox",
    "Ctrl+Shift+I",
    "Go to Inbox",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Mail",
    "Ctrl+1",
    "Switch to Mail",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_OUTLOOK,
    "Calendar",
    "Ctrl+2",
    "Switch to Calendar",
    GROUP_NAVIGATION,
  ),

  buildingDefaultLabel(
    SET_ONENOTE,
    "New page",
    "Ctrl+N",
    "Add a page",
    GROUP_NOTES,
  ),
  buildingDefaultLabel(
    SET_ONENOTE,
    "New subpage",
    "Ctrl+Shift+N",
    "Add a subpage",
    GROUP_NOTES,
  ),
  buildingDefaultLabel(
    SET_ONENOTE,
    "Search",
    "Ctrl+E",
    "Search notes",
    GROUP_NOTES,
  ),
  buildingDefaultLabel(
    SET_ONENOTE,
    "To-do",
    "Ctrl+1",
    "Toggle a to-do tag",
    GROUP_NOTES,
  ),
  buildingDefaultLabel(
    SET_ONENOTE,
    "Save",
    "Ctrl+S",
    "Save the notebook",
    GROUP_NOTES,
  ),
  buildingDefaultLabel(
    SET_ONENOTE,
    "Date and time",
    "Alt+Shift+F",
    "Insert the date and time",
    GROUP_NOTES,
  ),
  buildingDefaultLabel(
    SET_ONENOTE,
    "Bold",
    "Ctrl+B",
    "Bold the selection",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_ONENOTE,
    "Italic",
    "Ctrl+I",
    "Italicize the selection",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_ONENOTE,
    "Underline",
    "Ctrl+U",
    "Underline the selection",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_ONENOTE,
    "Highlight",
    "Ctrl+Alt+H",
    "Highlight the selection",
    GROUP_FORMATTING,
  ),
  buildingDefaultLabel(
    SET_ONENOTE,
    "Heading 1",
    "Ctrl+Alt+1",
    "Apply Heading 1",
    GROUP_FORMATTING,
  ),

  buildingDefaultLabel(
    SET_CURSOR,
    "Command palette",
    "Ctrl+Shift+P",
    "Open the command palette",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Quick open",
    "Ctrl+P",
    "Open a file by name",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Go to line",
    "Ctrl+G",
    "Jump to a line number",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Find",
    "Ctrl+F",
    "Search in the current file",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Replace",
    "Ctrl+H",
    "Find and replace in the file",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Find in files",
    "Ctrl+Shift+F",
    "Search across the workspace",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Go to symbol",
    "Ctrl+Shift+O",
    "Jump to a symbol in the file",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Toggle sidebar",
    "Ctrl+B",
    "Show or hide the side bar",
  ),
  buildingDefaultLabel(SET_CURSOR, "Terminal", "Ctrl+`", "Toggle the terminal"),
  buildingDefaultLabel(
    SET_CURSOR,
    "New terminal",
    "Ctrl+Shift+`",
    "Open a new terminal",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Split editor",
    "Ctrl+\\",
    "Split the current editor",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Close editor",
    "Ctrl+W",
    "Close the current file",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Next editor",
    "Ctrl+PageDown",
    "Switch to the next tab",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Previous editor",
    "Ctrl+PageUp",
    "Switch to the previous tab",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Select next match",
    "Ctrl+D",
    "Add the next match to the selection",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Rename symbol",
    "F2",
    "Rename the current symbol",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Go to definition",
    "F12",
    "Jump to the definition",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Peek definition",
    "Alt+F12",
    "Peek at the definition",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Format document",
    "Shift+Alt+F",
    "Format the current file",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Move line up",
    "Alt+Up",
    "Move the current line up",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Move line down",
    "Alt+Down",
    "Move the current line down",
  ),
  buildingDefaultLabel(SET_CURSOR, "Settings", "Ctrl+,", "Open settings"),
  buildingDefaultLabel(
    SET_CURSOR,
    "Explorer",
    "Ctrl+Shift+E",
    "Show the file tree",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Inline edit",
    "Ctrl+K",
    "Edit the selection with AI",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Chat",
    "Ctrl+L",
    "Open chat or ask about the selection",
  ),
  buildingDefaultLabel(SET_CURSOR, "Agent", "Ctrl+I", "Open Agent or Composer"),
  buildingDefaultLabel(
    SET_CURSOR,
    "Agent layout",
    "Ctrl+E",
    "Switch to the Agent layout",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Mode menu",
    "Ctrl+.",
    "Switch between Agent, Ask, and Plan",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Add to chat",
    "Ctrl+Shift+L",
    "Add the selection to chat",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Side chat",
    "Ctrl+Shift+S",
    "Open a side chat without leaving the agent",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Cursor settings",
    "Ctrl+Shift+J",
    "Open Cursor settings",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Toggle AI input",
    "Ctrl+Shift+K",
    "Focus or leave the inline edit box",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Accept suggestion",
    "Tab",
    "Accept the current AI suggestion",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Rotate modes",
    "Shift+Tab",
    "Cycle Agent, Ask, and Plan",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Accept all",
    "Ctrl+Enter",
    "Accept all AI changes or submit chat",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Reject all",
    "Ctrl+Backspace",
    "Reject all AI changes",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Accept word",
    "Ctrl+Right",
    "Accept the next word of a suggestion",
  ),
  buildingDefaultLabel(
    SET_CURSOR,
    "Cycle models",
    "Ctrl+/",
    "Switch the active AI model",
  ),

  buildingDefaultLabel(
    SET_CHROME,
    "New tab",
    "Ctrl+T",
    "Open a tab",
    GROUP_TABS,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Close tab",
    "Ctrl+W",
    "Close the tab",
    GROUP_TABS,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Reopen tab",
    "Ctrl+Shift+T",
    "Restore the last tab",
    GROUP_TABS,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Next tab",
    "Ctrl+Tab",
    "Switch to the next tab",
    GROUP_TABS,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Previous tab",
    "Ctrl+Shift+Tab",
    "Switch to the previous tab",
    GROUP_TABS,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Address bar",
    "Ctrl+L",
    "Focus the URL",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Back",
    "Alt+Left",
    "Go back",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Forward",
    "Alt+Right",
    "Go forward",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Home",
    "Alt+Home",
    "Open the home page",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Refresh",
    "Ctrl+R",
    "Reload the page",
    GROUP_PAGE,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Hard refresh",
    "Ctrl+Shift+R",
    "Reload and skip the cache",
    GROUP_PAGE,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Find",
    "Ctrl+F",
    "Find on the page",
    GROUP_PAGE,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Fullscreen",
    "F11",
    "Toggle fullscreen",
    GROUP_PAGE,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Zoom in",
    "Ctrl+=",
    "Make the page larger",
    GROUP_PAGE,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Zoom out",
    "Ctrl+Minus",
    "Make the page smaller",
    GROUP_PAGE,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "New window",
    "Ctrl+N",
    "Open a window",
    GROUP_WINDOW,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Incognito",
    "Ctrl+Shift+N",
    "Open a private window",
    GROUP_WINDOW,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Bookmark",
    "Ctrl+D",
    "Bookmark this page",
    GROUP_LIBRARY,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "History",
    "Ctrl+H",
    "Open history",
    GROUP_LIBRARY,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Downloads",
    "Ctrl+J",
    "Open downloads",
    GROUP_LIBRARY,
  ),
  buildingDefaultLabel(
    SET_CHROME,
    "Bookmarks manager",
    "Ctrl+Shift+O",
    "Open the bookmarks manager",
    GROUP_LIBRARY,
  ),

  buildingDefaultLabel(SET_IE, "New tab", "Ctrl+T", "Open a tab", GROUP_TABS),
  buildingDefaultLabel(
    SET_IE,
    "Close",
    "Ctrl+W",
    "Close the tab or window",
    GROUP_TABS,
  ),
  buildingDefaultLabel(
    SET_IE,
    "Address bar",
    "Alt+D",
    "Focus the URL",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(SET_IE, "Back", "Alt+Left", "Go back", GROUP_NAVIGATION),
  buildingDefaultLabel(
    SET_IE,
    "Forward",
    "Alt+Right",
    "Go forward",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_IE,
    "Home",
    "Alt+Home",
    "Open the home page",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(SET_IE, "Refresh", "F5", "Reload the page", GROUP_PAGE),
  buildingDefaultLabel(
    SET_IE,
    "Find",
    "Ctrl+F",
    "Find on the page",
    GROUP_PAGE,
  ),
  buildingDefaultLabel(
    SET_IE,
    "Fullscreen",
    "F11",
    "Toggle fullscreen",
    GROUP_PAGE,
  ),
  buildingDefaultLabel(
    SET_IE,
    "New window",
    "Ctrl+N",
    "Open a window",
    GROUP_WINDOW,
  ),
  buildingDefaultLabel(
    SET_IE,
    "Favorites",
    "Ctrl+I",
    "Open favorites",
    GROUP_LIBRARY,
  ),
  buildingDefaultLabel(
    SET_IE,
    "History",
    "Ctrl+H",
    "Open history",
    GROUP_LIBRARY,
  ),

  buildingDefaultLabel(
    SET_EXPLORER,
    "New folder",
    "Ctrl+Shift+N",
    "Create a folder",
    GROUP_FILES,
  ),
  buildingDefaultLabel(
    SET_EXPLORER,
    "Rename",
    "F2",
    "Rename the item",
    GROUP_FILES,
  ),
  buildingDefaultLabel(
    SET_EXPLORER,
    "Properties",
    "Alt+Enter",
    "Open properties",
    GROUP_FILES,
  ),
  buildingDefaultLabel(
    SET_EXPLORER,
    "Delete",
    "Delete",
    "Delete the item",
    GROUP_FILES,
  ),
  buildingDefaultLabel(
    SET_EXPLORER,
    "Permanent delete",
    "Shift+Delete",
    "Delete without the Recycle Bin",
    GROUP_FILES,
  ),
  buildingDefaultLabel(
    SET_EXPLORER,
    "New window",
    "Ctrl+N",
    "Open another window",
    GROUP_WINDOW,
  ),
  buildingDefaultLabel(
    SET_EXPLORER,
    "Preview pane",
    "Alt+P",
    "Show or hide the preview pane",
    GROUP_VIEW,
  ),
  buildingDefaultLabel(
    SET_EXPLORER,
    "Address bar",
    "Alt+D",
    "Focus the path",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_EXPLORER,
    "Up one level",
    "Alt+Up",
    "Go to the parent folder",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_EXPLORER,
    "Back",
    "Alt+Left",
    "Go back",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_EXPLORER,
    "Forward",
    "Alt+Right",
    "Go forward",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_EXPLORER,
    "Refresh",
    "F5",
    "Refresh the folder",
    GROUP_NAVIGATION,
  ),
  buildingDefaultLabel(
    SET_EXPLORER,
    "Search",
    "Ctrl+F",
    "Focus the search box",
    GROUP_NAVIGATION,
  ),

  buildingDefaultLabel(
    SET_KEYVIZ,
    "Toggle overlay",
    "Shift+F10",
    "Show or hide Keyviz. Change this in General if you remapped it.",
    GROUP_KEYVIZ,
  ),
  buildingDefaultLabel(
    SET_KEYVIZ,
    "Open settings",
    "Ctrl+Alt+Q",
    "Show or hide Keyviz settings",
    GROUP_KEYVIZ,
  ),
  buildingDefaultLabel(
    SET_KEYVIZ,
    "Draw mode",
    "Ctrl+Alt+D",
    "Draw on the screen. Escape or Ctrl+Alt+D leaves.",
    GROUP_KEYVIZ,
  ),
];

const labelingKey = (label: Pick<HotkeyLabel, "set" | "combo">) =>
  `${label.set.toLowerCase()}|${label.combo.toLowerCase()}`;

const LEGACY_CATCHALL_GROUPS = new Set(["", "Browser"]);

const groupKey = (set: string, combo: string) => labelingKey({ set, combo });

const FUNCTION_GROUP_BY_KEY: Record<string, string> = {
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+C")]: GROUP_CLIPBOARD,
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+V")]: GROUP_CLIPBOARD,
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+X")]: GROUP_CLIPBOARD,
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+Z")]: GROUP_EDITING,
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+Y")]: GROUP_EDITING,
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+A")]: GROUP_EDITING,
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+F")]: GROUP_EDITING,
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+S")]: GROUP_FILE,
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+O")]: GROUP_FILE,
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+N")]: GROUP_FILE,
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+P")]: GROUP_FILE,
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+W")]: GROUP_FILE,
  [groupKey(DEFAULT_HOTKEY_SET, "Alt+F4")]: GROUP_WINDOW,
  [groupKey(DEFAULT_HOTKEY_SET, "Alt+Tab")]: GROUP_WINDOW,
  [groupKey(DEFAULT_HOTKEY_SET, "F5")]: GROUP_NAVIGATION,
  [groupKey(DEFAULT_HOTKEY_SET, "Ctrl+L")]: GROUP_NAVIGATION,
  [groupKey(DEFAULT_HOTKEY_SET, "Shift+(char)")]: GROUP_TYPING,

  [groupKey(SET_WORD, "Ctrl+B")]: GROUP_FORMATTING,
  [groupKey(SET_WORD, "Ctrl+I")]: GROUP_FORMATTING,
  [groupKey(SET_WORD, "Ctrl+U")]: GROUP_FORMATTING,
  [groupKey(SET_WORD, "Ctrl+E")]: GROUP_FORMATTING,
  [groupKey(SET_WORD, "Ctrl+L")]: GROUP_FORMATTING,
  [groupKey(SET_WORD, "Ctrl+R")]: GROUP_FORMATTING,
  [groupKey(SET_WORD, "Ctrl+Shift+C")]: GROUP_FORMATTING,
  [groupKey(SET_WORD, "Ctrl+Shift+V")]: GROUP_FORMATTING,
  [groupKey(SET_WORD, "Ctrl+S")]: GROUP_FILE,
  [groupKey(SET_WORD, "Ctrl+O")]: GROUP_FILE,
  [groupKey(SET_WORD, "Ctrl+P")]: GROUP_FILE,
  [groupKey(SET_WORD, "Ctrl+N")]: GROUP_FILE,
  [groupKey(SET_WORD, "Ctrl+W")]: GROUP_FILE,
  [groupKey(SET_WORD, "Ctrl+F")]: GROUP_EDITING,
  [groupKey(SET_WORD, "Ctrl+H")]: GROUP_EDITING,
  [groupKey(SET_WORD, "Ctrl+K")]: GROUP_EDITING,
  [groupKey(SET_WORD, "Ctrl+G")]: GROUP_NAVIGATION,
  [groupKey(SET_WORD, "F7")]: GROUP_PROOFING,
  [groupKey(SET_WORD, "Shift+F7")]: GROUP_PROOFING,

  [groupKey(SET_POWERPOINT, "F5")]: GROUP_SLIDESHOW,
  [groupKey(SET_POWERPOINT, "Shift+F5")]: GROUP_SLIDESHOW,
  [groupKey(SET_POWERPOINT, "Escape")]: GROUP_SLIDESHOW,
  [groupKey(SET_POWERPOINT, "B")]: GROUP_SLIDESHOW,
  [groupKey(SET_POWERPOINT, "W")]: GROUP_SLIDESHOW,
  [groupKey(SET_POWERPOINT, "PageDown")]: GROUP_SLIDESHOW,
  [groupKey(SET_POWERPOINT, "PageUp")]: GROUP_SLIDESHOW,
  [groupKey(SET_POWERPOINT, "Ctrl+M")]: GROUP_EDITING,
  [groupKey(SET_POWERPOINT, "Ctrl+D")]: GROUP_EDITING,
  [groupKey(SET_POWERPOINT, "Ctrl+B")]: GROUP_FORMATTING,
  [groupKey(SET_POWERPOINT, "Ctrl+I")]: GROUP_FORMATTING,
  [groupKey(SET_POWERPOINT, "Ctrl+S")]: GROUP_FILE,
  [groupKey(SET_POWERPOINT, "Ctrl+O")]: GROUP_FILE,
  [groupKey(SET_POWERPOINT, "Ctrl+P")]: GROUP_FILE,
  [groupKey(SET_POWERPOINT, "Ctrl+N")]: GROUP_FILE,
  [groupKey(SET_POWERPOINT, "Ctrl+G")]: GROUP_ARRANGE,
  [groupKey(SET_POWERPOINT, "Ctrl+Shift+G")]: GROUP_ARRANGE,

  [groupKey(SET_EXCEL, "F2")]: GROUP_EDITING,
  [groupKey(SET_EXCEL, "Ctrl+1")]: GROUP_EDITING,
  [groupKey(SET_EXCEL, "Ctrl+F")]: GROUP_EDITING,
  [groupKey(SET_EXCEL, "Ctrl+H")]: GROUP_EDITING,
  [groupKey(SET_EXCEL, "Ctrl+D")]: GROUP_EDITING,
  [groupKey(SET_EXCEL, "Ctrl+R")]: GROUP_EDITING,
  [groupKey(SET_EXCEL, "Ctrl+B")]: GROUP_FORMATTING,
  [groupKey(SET_EXCEL, "Alt+=")]: GROUP_DATA,
  [groupKey(SET_EXCEL, "Ctrl+T")]: GROUP_DATA,
  [groupKey(SET_EXCEL, "Ctrl+Shift+L")]: GROUP_DATA,
  [groupKey(SET_EXCEL, "Ctrl+Space")]: GROUP_DATA,
  [groupKey(SET_EXCEL, "Shift+Space")]: GROUP_DATA,
  [groupKey(SET_EXCEL, "Ctrl+`")]: GROUP_DATA,
  [groupKey(SET_EXCEL, "Shift+F3")]: GROUP_DATA,
  [groupKey(SET_EXCEL, "F5")]: GROUP_NAVIGATION,
  [groupKey(SET_EXCEL, "Ctrl+PageDown")]: GROUP_NAVIGATION,
  [groupKey(SET_EXCEL, "Ctrl+PageUp")]: GROUP_NAVIGATION,
  [groupKey(SET_EXCEL, "Ctrl+S")]: GROUP_FILE,
  [groupKey(SET_EXCEL, "Ctrl+O")]: GROUP_FILE,
  [groupKey(SET_EXCEL, "Ctrl+N")]: GROUP_FILE,
  [groupKey(SET_EXCEL, "Ctrl+P")]: GROUP_FILE,

  [groupKey(SET_OUTLOOK, "Ctrl+N")]: GROUP_MAIL,
  [groupKey(SET_OUTLOOK, "Ctrl+R")]: GROUP_MAIL,
  [groupKey(SET_OUTLOOK, "Ctrl+Shift+R")]: GROUP_MAIL,
  [groupKey(SET_OUTLOOK, "Ctrl+F")]: GROUP_MAIL,
  [groupKey(SET_OUTLOOK, "Ctrl+Enter")]: GROUP_MAIL,
  [groupKey(SET_OUTLOOK, "Delete")]: GROUP_MAIL,
  [groupKey(SET_OUTLOOK, "Ctrl+E")]: GROUP_MAIL,
  [groupKey(SET_OUTLOOK, "Ctrl+U")]: GROUP_MAIL,
  [groupKey(SET_OUTLOOK, "Ctrl+Shift+G")]: GROUP_MAIL,
  [groupKey(SET_OUTLOOK, "Ctrl+Shift+B")]: GROUP_MAIL,
  [groupKey(SET_OUTLOOK, "F9")]: GROUP_MAIL,
  [groupKey(SET_OUTLOOK, "Ctrl+Shift+A")]: GROUP_CALENDAR,
  [groupKey(SET_OUTLOOK, "Ctrl+Shift+I")]: GROUP_NAVIGATION,
  [groupKey(SET_OUTLOOK, "Ctrl+1")]: GROUP_NAVIGATION,
  [groupKey(SET_OUTLOOK, "Ctrl+2")]: GROUP_NAVIGATION,

  [groupKey(SET_ONENOTE, "Ctrl+N")]: GROUP_NOTES,
  [groupKey(SET_ONENOTE, "Ctrl+Shift+N")]: GROUP_NOTES,
  [groupKey(SET_ONENOTE, "Ctrl+E")]: GROUP_NOTES,
  [groupKey(SET_ONENOTE, "Ctrl+1")]: GROUP_NOTES,
  [groupKey(SET_ONENOTE, "Ctrl+S")]: GROUP_NOTES,
  [groupKey(SET_ONENOTE, "Alt+Shift+F")]: GROUP_NOTES,
  [groupKey(SET_ONENOTE, "Ctrl+B")]: GROUP_FORMATTING,
  [groupKey(SET_ONENOTE, "Ctrl+I")]: GROUP_FORMATTING,
  [groupKey(SET_ONENOTE, "Ctrl+U")]: GROUP_FORMATTING,
  [groupKey(SET_ONENOTE, "Ctrl+Alt+H")]: GROUP_FORMATTING,
  [groupKey(SET_ONENOTE, "Ctrl+Alt+1")]: GROUP_FORMATTING,

  [groupKey(SET_CURSOR, "Ctrl+Shift+P")]: GROUP_GENERAL,
  [groupKey(SET_CURSOR, "Ctrl+,")]: GROUP_GENERAL,
  [groupKey(SET_CURSOR, "Ctrl+P")]: GROUP_NAVIGATION,
  [groupKey(SET_CURSOR, "Ctrl+G")]: GROUP_NAVIGATION,
  [groupKey(SET_CURSOR, "Ctrl+Shift+O")]: GROUP_NAVIGATION,
  [groupKey(SET_CURSOR, "F12")]: GROUP_NAVIGATION,
  [groupKey(SET_CURSOR, "Alt+F12")]: GROUP_NAVIGATION,
  [groupKey(SET_CURSOR, "Ctrl+PageDown")]: GROUP_NAVIGATION,
  [groupKey(SET_CURSOR, "Ctrl+PageUp")]: GROUP_NAVIGATION,
  [groupKey(SET_CURSOR, "Ctrl+F")]: GROUP_EDITING,
  [groupKey(SET_CURSOR, "Ctrl+H")]: GROUP_EDITING,
  [groupKey(SET_CURSOR, "Ctrl+Shift+F")]: GROUP_EDITING,
  [groupKey(SET_CURSOR, "Ctrl+D")]: GROUP_EDITING,
  [groupKey(SET_CURSOR, "F2")]: GROUP_EDITING,
  [groupKey(SET_CURSOR, "Shift+Alt+F")]: GROUP_EDITING,
  [groupKey(SET_CURSOR, "Alt+Up")]: GROUP_EDITING,
  [groupKey(SET_CURSOR, "Alt+Down")]: GROUP_EDITING,
  [groupKey(SET_CURSOR, "Ctrl+W")]: GROUP_EDITING,
  [groupKey(SET_CURSOR, "Ctrl+B")]: GROUP_VIEW,
  [groupKey(SET_CURSOR, "Ctrl+`")]: GROUP_VIEW,
  [groupKey(SET_CURSOR, "Ctrl+Shift+`")]: GROUP_VIEW,
  [groupKey(SET_CURSOR, "Ctrl+\\")]: GROUP_VIEW,
  [groupKey(SET_CURSOR, "Ctrl+Shift+E")]: GROUP_VIEW,
  [groupKey(SET_CURSOR, "Ctrl+K")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Ctrl+L")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Ctrl+I")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Ctrl+E")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Ctrl+.")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Ctrl+Shift+L")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Ctrl+Shift+S")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Ctrl+Shift+J")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Ctrl+Shift+K")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Tab")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Shift+Tab")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Ctrl+Enter")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Ctrl+Backspace")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Ctrl+Right")]: GROUP_AI,
  [groupKey(SET_CURSOR, "Ctrl+/")]: GROUP_AI,

  [groupKey(SET_CHROME, "Ctrl+T")]: GROUP_TABS,
  [groupKey(SET_CHROME, "Ctrl+W")]: GROUP_TABS,
  [groupKey(SET_CHROME, "Ctrl+Shift+T")]: GROUP_TABS,
  [groupKey(SET_CHROME, "Ctrl+Tab")]: GROUP_TABS,
  [groupKey(SET_CHROME, "Ctrl+Shift+Tab")]: GROUP_TABS,
  [groupKey(SET_CHROME, "Ctrl+L")]: GROUP_NAVIGATION,
  [groupKey(SET_CHROME, "Alt+Left")]: GROUP_NAVIGATION,
  [groupKey(SET_CHROME, "Alt+Right")]: GROUP_NAVIGATION,
  [groupKey(SET_CHROME, "Alt+Home")]: GROUP_NAVIGATION,
  [groupKey(SET_CHROME, "Ctrl+R")]: GROUP_PAGE,
  [groupKey(SET_CHROME, "Ctrl+Shift+R")]: GROUP_PAGE,
  [groupKey(SET_CHROME, "Ctrl+F")]: GROUP_PAGE,
  [groupKey(SET_CHROME, "F11")]: GROUP_PAGE,
  [groupKey(SET_CHROME, "Ctrl+=")]: GROUP_PAGE,
  [groupKey(SET_CHROME, "Ctrl+Minus")]: GROUP_PAGE,
  [groupKey(SET_CHROME, "Ctrl+N")]: GROUP_WINDOW,
  [groupKey(SET_CHROME, "Ctrl+Shift+N")]: GROUP_WINDOW,
  [groupKey(SET_CHROME, "Ctrl+D")]: GROUP_LIBRARY,
  [groupKey(SET_CHROME, "Ctrl+H")]: GROUP_LIBRARY,
  [groupKey(SET_CHROME, "Ctrl+J")]: GROUP_LIBRARY,
  [groupKey(SET_CHROME, "Ctrl+Shift+O")]: GROUP_LIBRARY,

  [groupKey(SET_IE, "Ctrl+T")]: GROUP_TABS,
  [groupKey(SET_IE, "Ctrl+W")]: GROUP_TABS,
  [groupKey(SET_IE, "Alt+D")]: GROUP_NAVIGATION,
  [groupKey(SET_IE, "Alt+Left")]: GROUP_NAVIGATION,
  [groupKey(SET_IE, "Alt+Right")]: GROUP_NAVIGATION,
  [groupKey(SET_IE, "Alt+Home")]: GROUP_NAVIGATION,
  [groupKey(SET_IE, "F5")]: GROUP_PAGE,
  [groupKey(SET_IE, "Ctrl+F")]: GROUP_PAGE,
  [groupKey(SET_IE, "F11")]: GROUP_PAGE,
  [groupKey(SET_IE, "Ctrl+N")]: GROUP_WINDOW,
  [groupKey(SET_IE, "Ctrl+I")]: GROUP_LIBRARY,
  [groupKey(SET_IE, "Ctrl+H")]: GROUP_LIBRARY,

  [groupKey(SET_EXPLORER, "Ctrl+Shift+N")]: GROUP_FILES,
  [groupKey(SET_EXPLORER, "F2")]: GROUP_FILES,
  [groupKey(SET_EXPLORER, "Alt+Enter")]: GROUP_FILES,
  [groupKey(SET_EXPLORER, "Delete")]: GROUP_FILES,
  [groupKey(SET_EXPLORER, "Shift+Delete")]: GROUP_FILES,
  [groupKey(SET_EXPLORER, "Ctrl+N")]: GROUP_WINDOW,
  [groupKey(SET_EXPLORER, "Alt+P")]: GROUP_VIEW,
  [groupKey(SET_EXPLORER, "Alt+D")]: GROUP_NAVIGATION,
  [groupKey(SET_EXPLORER, "Alt+Up")]: GROUP_NAVIGATION,
  [groupKey(SET_EXPLORER, "Alt+Left")]: GROUP_NAVIGATION,
  [groupKey(SET_EXPLORER, "Alt+Right")]: GROUP_NAVIGATION,
  [groupKey(SET_EXPLORER, "F5")]: GROUP_NAVIGATION,
  [groupKey(SET_EXPLORER, "Ctrl+F")]: GROUP_NAVIGATION,

  [groupKey(SET_KEYVIZ, "Shift+F10")]: GROUP_KEYVIZ,
  [groupKey(SET_KEYVIZ, "Ctrl+Alt+Q")]: GROUP_KEYVIZ,
  [groupKey(SET_KEYVIZ, "Ctrl+Alt+D")]: GROUP_KEYVIZ,
};

/**
 * Starter shortcuts with function groups filled in.
 */
export const DEFAULT_HOTKEY_LABELS: HotkeyLabel[] =
  RAW_DEFAULT_HOTKEY_LABELS.map((label) => ({
    ...label,
    group: label.group || FUNCTION_GROUP_BY_KEY[labelingKey(label)] || "",
  }));

/**
 * Adds missing starter sets and labels. Backfills empty function groups.
 */
const LEGACY_DRAW_COMBO = "ctrl+alt+y";
const DRAW_MODE_COMBO = "Ctrl+Alt+D";
const DRAW_MODE_LABEL = "Draw mode";

export const mergingDefaultHotkeys = (
  sets: HotkeySet[],
  labels: HotkeyLabel[],
): { sets: HotkeySet[]; labels: HotkeyLabel[] } => {
  const nextSets = [...sets];
  for (const set of DEFAULT_HOTKEY_SETS) {
    if (!nextSets.some((row) => row.name === set.name)) {
      nextSets.push(set);
    }
  }

  const nextLabels = labels.map((label) => ({
    ...label,
    description: label.description ?? "",
    group: label.group ?? "",
    combo:
      label.set === SET_KEYVIZ &&
      label.name === DRAW_MODE_LABEL &&
      label.combo.toLowerCase() === LEGACY_DRAW_COMBO
        ? DRAW_MODE_COMBO
        : label.combo,
  }));
  const seen = new Set(nextLabels.map(labelingKey));
  for (const label of DEFAULT_HOTKEY_LABELS) {
    const key = labelingKey(label);
    if (seen.has(key)) {
      const index = nextLabels.findIndex((row) => labelingKey(row) === key);
      if (
        index >= 0 &&
        label.group &&
        LEGACY_CATCHALL_GROUPS.has(nextLabels[index].group)
      ) {
        nextLabels[index] = { ...nextLabels[index], group: label.group };
      }
      continue;
    }
    nextLabels.push(label);
    seen.add(key);
  }

  return { sets: nextSets, labels: nextLabels };
};
